### ISSUE TITLE
Investigate if Faces(Global)ResourceServlet can be subclassed to suppress Broken Pipe exceptions

### ISSUE THREAD

**Issue by jesse-gallagher** [jesse-gallagher/xpages-runtime#2]
This started showing up in recent years both on Domino and in this runtime, and here it could be potentially squelched.

```
[err] com.ibm.ws.webcontainer.webapp.WebAppErrorReport: java.io.IOException: Broken pipe
[err] 	at com.ibm.ws.webcontainer.webapp.WebAppErrorReport.constructErrorReport(WebAppErrorReport.java:157)
[err] 	at [internal classes]
[err] 	at jakarta.ODAFilter.doFilter(ODAFilter.java:112)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[err] 	at java.lang.Thread.run(Thread.java:748)
[err] Caused by: java.io.IOException: Broken pipe
[err] 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
[err] 	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
[err] 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
[err] 	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
[err] 	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
[err] 	at com.ibm.ws.tcpchannel.internal.NioSocketIOChannel.write(NioSocketIOChannel.java:201)
[err] 	at [internal classes]
[err] 	at com.ibm.commons.util.io.ByteStreamCache.copyTo(ByteStreamCache.java:231)
[err] 	at com.ibm.xsp.minifier.MinifierResourceProvider$MinifiedResource._writeResource(MinifierResourceProvider.java:128)
[err] 	at com.ibm.xsp.minifier.MinifierResourceProvider$MinifiedResource.writeResource(MinifierResourceProvider.java:103)
[err] 	at com.ibm.xsp.minifier.MinifierResourceProvider$MinifiedResource.write(MinifierResourceProvider.java:80)
[err] 	at com.ibm.xsp.webapp.FacesResourceServlet.doGet(FacesResourceServlet.java:109)
[err] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
[err] 	at [internal classes]
[err] 	at com.ibm.xsp.webapp.FacesGlobalResourceServlet.service(FacesGlobalResourceServlet.java:83)
[err] 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
[err] 	at [internal classes]
[err] 	... 28 more
```

**Comment by jesse-gallagher** [comment]
It's now subclassed, so it can be handled in `JakartaGlobalResourceServlet`:

```
com.ibm.ws.webcontainer.webapp.WebAppErrorReport: java.io.IOException: Broken pipe[003247:000060-00007F28A8CBD700] 06/10/2020 10:04:42 AM  WLP:  at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
 at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
 at sun.nio.ch.IOUtil.write(IOUtil.java:148)
 at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
 at java.nio.channels.SocketChannel.write(SocketChannel.java:502)
 at com.ibm.ws.tcpchannel.internal.NioSocketIOChannel.write(NioSocketIOChannel.java:205)
 at [internal classes]
 at java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:168)
 at com.ibm.xsp.webapp.resources.URLResourceProvider$URLResource.writeData(URLResourceProvider.java:87)
 at com.ibm.xsp.webapp.resources.AbstractResourceProvider$AbstractResource.write(AbstractResourceProvider.java:160)
 at com.ibm.xsp.webapp.FacesResourceServlet.doGet(FacesResourceServlet.java:109)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
 at com.ibm.xsp.webapp.FacesGlobalResourceServlet.service(FacesGlobalResourceServlet.java:83)
 at org.openntf.xpages.runtime.JakartaGlobalFacesResourceServlet.service(JakartaGlobalFacesResourceServlet.java:34)
 at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
 at [internal classes]
 at net.cmssite.jakarta.ODAFilter.doFilter(ODAFilter.java:112)
 at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
 at [internal classes]
Caused by: java.io.IOException: Broken pipe
 ... 21 more
```
